apiVersion: v2
name: yarilo
description: Production-grade IMAP/SMTP/JMAP mail server
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - imap
  - smtp
  - mail
home: https://github.com/0kaba0hub/yarilo
sources:
  - https://github.com/0kaba0hub/yarilo
