version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - noctx

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/0kaba0hub/yarilo

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
        - unparam
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
