{{- $cert := .Values.components.director.tls.certificate }}
{{- $secret := .Values.components.director.tls.secretName }}
{{- if and $cert.enabled $secret }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "yarilo.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.labels" . | nindent 4 }}
spec:
  secretName: {{ $secret }}
  issuerRef:
    kind: {{ $cert.issuerRef.kind }}
    name: {{ $cert.issuerRef.name }}
  dnsNames:
    {{- range $cert.dnsNames }}
    - {{ . | quote }}
    {{- end }}
  {{- with $cert.duration }}
  duration: {{ . }}
  {{- end }}
  {{- with $cert.renewBefore }}
  renewBefore: {{ . }}
  {{- end }}
{{- end }}
