apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yarilo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.labels" . | nindent 4 }}
data:
  yarilo.yaml: |
    mode: single

    general:
      ssl:
        {{- if .Values.tls.secretName }}
        tls_cert: /etc/yarilo/tls/tls.crt
        tls_key: /etc/yarilo/tls/tls.key
        {{- else }}
        tls_cert: ""
        tls_key: ""
        {{- end }}
        tls_min_version: TLS1.2
      haproxy:
        timeout: {{ .Values.general.haproxy.timeout }}
        trusted_nets:
          {{- range .Values.general.haproxy.trustedNets }}
          - {{ . | quote }}
          {{- end }}
      xclient:
        trusted_nets:
          {{- range .Values.general.xclient.trustedNets }}
          - {{ . | quote }}
          {{- end }}
      limits:
        mail_max_userip_connections: {{ .Values.general.limits.maxUserIPConnections }}

    services:
      imaps:
        enabled: {{ .Values.services.imaps.enabled }}
        port: {{ .Values.services.imaps.port }}
        ssl_mode: ssl
        haproxy_protocol: {{ .Values.general.haproxy.enabled }}
        xclient_protocol: {{ .Values.general.xclient.enabled }}
        disable_plaintext_auth: {{ .Values.services.imaps.disablePlainAuth }}
      imap:
        enabled: {{ .Values.services.imap.enabled }}
        port: {{ .Values.services.imap.port }}
        ssl_mode: starttls
        haproxy_protocol: {{ .Values.general.haproxy.enabled }}
        xclient_protocol: {{ .Values.general.xclient.enabled }}
        disable_plaintext_auth: {{ .Values.services.imap.disablePlainAuth }}
      submission:
        enabled: {{ .Values.services.submission.enabled }}
        port: {{ .Values.services.submission.port }}
        ssl_mode: starttls
        haproxy_protocol: {{ .Values.general.haproxy.enabled }}
        xclient_protocol: false
        disable_plaintext_auth: {{ .Values.services.submission.disablePlainAuth }}
      submissions:
        enabled: {{ .Values.services.submissions.enabled }}
        port: {{ .Values.services.submissions.port }}
        ssl_mode: ssl
        haproxy_protocol: {{ .Values.general.haproxy.enabled }}
        xclient_protocol: false
        disable_plaintext_auth: {{ .Values.services.submissions.disablePlainAuth }}
      pop3:
        enabled: {{ .Values.services.pop3.enabled }}
        port: {{ .Values.services.pop3.port }}
        ssl_mode: starttls
        haproxy_protocol: {{ .Values.general.haproxy.enabled }}
        xclient_protocol: {{ .Values.general.xclient.enabled }}
      pop3s:
        enabled: {{ .Values.services.pop3s.enabled }}
        port: {{ .Values.services.pop3s.port }}
        ssl_mode: ssl
        haproxy_protocol: {{ .Values.general.haproxy.enabled }}
        xclient_protocol: {{ .Values.general.xclient.enabled }}
      lmtp:
        enabled: {{ .Values.services.lmtp.enabled }}
        port: {{ .Values.services.lmtp.containerPort | default .Values.services.lmtp.port }}
        ssl_mode: "no"
        haproxy_protocol: {{ .Values.general.haproxy.enabled }}
        xclient_protocol: {{ .Values.general.xclient.enabled }}

    protocol:
      imap:
        imap_idle_notify_interval: {{ .Values.protocol.imap.idleNotifyInterval }}
        imap_max_line_length: {{ .Values.protocol.imap.maxLineLength }}
        imap_id_send: {{ .Values.protocol.imap.idSend | quote }}
        login_greeting: {{ .Values.protocol.imap.loginGreeting | quote }}
        imap_logout_format: {{ .Values.protocol.imap.logoutFormat | quote }}
        {{- with .Values.protocol.imap.clientWorkarounds }}
        client_workarounds:
          {{- range . }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}

      submission:
        hostname: {{ .Values.protocol.submission.hostname | default .Values.hostname | quote }}
        max_message_size: {{ int64 .Values.protocol.submission.maxMessageSize }}
        max_line_length: {{ int .Values.protocol.submission.maxLineLength }}
        max_recipients: {{ .Values.protocol.submission.maxRecipients }}
        recipient_delimiter: {{ .Values.protocol.submission.recipientDelimiter | quote }}
        submission_add_received_header: {{ .Values.protocol.submission.addReceivedHeader }}
        {{- with .Values.protocol.submission.clientWorkarounds }}
        client_workarounds:
          {{- range . }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
        relay:
          host: {{ .Values.protocol.submission.relay.host | quote }}
          port: {{ .Values.protocol.submission.relay.port }}
          user: {{ .Values.protocol.submission.relay.user | quote }}
          password: {{ .Values.protocol.submission.relay.password | quote }}
          ssl: {{ .Values.protocol.submission.relay.ssl | quote }}
          ssl_verify: {{ .Values.protocol.submission.relay.sslVerify }}
          trusted: {{ .Values.protocol.submission.relay.trusted }}
          connect_timeout: {{ .Values.protocol.submission.relay.connectTimeout }}
          command_timeout: {{ .Values.protocol.submission.relay.commandTimeout }}

      lmtp:
        login_greeting: {{ .Values.protocol.lmtp.loginGreeting | quote }}
        add_received_header: {{ .Values.protocol.lmtp.addReceivedHeader }}
        save_to_detail_mailbox: {{ .Values.protocol.lmtp.saveToDetailMailbox }}
        hdr_delivery_address: {{ .Values.protocol.lmtp.hdrDeliveryAddress | quote }}
        verbose_replies: {{ .Values.protocol.lmtp.verboseReplies }}
        user_concurrency_limit: {{ .Values.protocol.lmtp.userConcurrencyLimit }}
        read_timeout: {{ .Values.protocol.lmtp.readTimeout }}
        write_timeout: {{ .Values.protocol.lmtp.writeTimeout }}
        {{- with .Values.protocol.lmtp.clientWorkarounds }}
        client_workarounds:
          {{- range . }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}

      pop3:
        pop3_no_flag_updates: {{ .Values.protocol.pop3.noFlagUpdates }}
        pop3_reuse_xuidl: {{ .Values.protocol.pop3.reuseXUIDL }}
        pop3_uidl_format: {{ .Values.protocol.pop3.uidlFormat | quote }}
        pop3_uidl_duplicates: {{ .Values.protocol.pop3.uidlDuplicates | quote }}
        pop3_enable_last: {{ .Values.protocol.pop3.enableLast }}
        pop3_delete_type: {{ .Values.protocol.pop3.deleteType | quote }}
        pop3_deleted_flag: {{ .Values.protocol.pop3.deletedFlag | quote }}

    auth:
      passdb:
        {{- range .Values.auth.passdb }}
        - driver: {{ .driver | quote }}
          dsn: {{ .dsn | quote }}
          {{- with .passwordQuery }}
          password_query: |
            {{- . | nindent 12 }}
          {{- end }}
          {{- with .userQuery }}
          user_query: |
            {{- . | nindent 12 }}
          {{- end }}
          {{- with .iterateQuery }}
          iterate_query: |
            {{- . | nindent 12 }}
          {{- end }}
          {{- with .defaultPassScheme }}
          default_pass_scheme: {{ . | quote }}
          {{- end }}
          {{- if .skipSchema }}
          skip_schema: true
          {{- end }}
        {{- end }}

    storage:
      mailbox: {{ .Values.storage.mailbox | quote }}
      maildir_root: {{ .Values.storage.maildirRoot | quote }}
      mail_home_template: {{ .Values.storage.mailHomeTemplate | quote }}
      index: {{ .Values.storage.index | quote }}
      index_dir: ""

    telemetry:
      listen: {{ .Values.telemetry.listen | quote }}

    log:
      level: {{ .Values.logLevel | quote }}
