{{- $imap := .Values.components.imap }}
{{- $pop3 := .Values.components.pop3 }}
{{- $lmtp := .Values.components.lmtp }}
{{- $p := coalesce (and $imap.enabled $imap.storage.persistence.enabled | ternary $imap.storage.persistence nil) (and $pop3.enabled $pop3.storage.persistence.enabled | ternary $pop3.storage.persistence nil) (and $lmtp.enabled $lmtp.storage.persistence.enabled | ternary $lmtp.storage.persistence nil) }}
{{- if $p }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "yarilo.fullname" . }}-mail
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $p.accessMode }}
  {{- if $p.storageClass }}
  storageClassName: {{ $p.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ $p.size }}
{{- end }}
