{{- $p := .Values.storage.persistence }}
{{- if $p }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "yarilo.fullname" . }}-mail
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $p.accessMode }}
  {{- if $p.storageClass }}
  storageClassName: {{ $p.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ $p.size }}
{{- end }}
