{{- if .Values.mysql.bundled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yarilo.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.componentLabels" (dict "root" . "component" "mysql") | nindent 4 }}
type: Opaque
stringData:
  MYSQL_DATABASE: {{ .Values.mysql.db | quote }}
  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.password | quote }}
  dsn: {{ printf "%s:%s@tcp(%s-mysql.%s.svc:3306)/%s?parseTime=true&charset=utf8mb4" .Values.mysql.user .Values.mysql.password (include "yarilo.fullname" .) .Release.Namespace .Values.mysql.db | quote }}
{{- end }}
