apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    {{- if .Values.services.imaps.enabled }}
    - name: imaps
      port: {{ .Values.services.imaps.port }}
      targetPort: imaps
      protocol: TCP
    {{- end }}
    {{- if .Values.services.imap.enabled }}
    - name: imap
      port: {{ .Values.services.imap.port }}
      targetPort: imap
      protocol: TCP
    {{- end }}
    {{- if .Values.services.submission.enabled }}
    - name: submission
      port: {{ .Values.services.submission.port }}
      targetPort: submission
      protocol: TCP
    {{- end }}
    {{- if .Values.services.submissions.enabled }}
    - name: submissions
      port: {{ .Values.services.submissions.port }}
      targetPort: submissions
      protocol: TCP
    {{- end }}
    {{- if .Values.services.pop3.enabled }}
    - name: pop3
      port: {{ .Values.services.pop3.port }}
      targetPort: pop3
      protocol: TCP
    {{- end }}
    {{- if .Values.services.pop3s.enabled }}
    - name: pop3s
      port: {{ .Values.services.pop3s.port }}
      targetPort: pop3s
      protocol: TCP
    {{- end }}
    {{- if .Values.services.lmtp.enabled }}
    - name: lmtp
      port: {{ .Values.services.lmtp.port }}
      targetPort: lmtp
      protocol: TCP
    {{- end }}
  selector:
    {{- include "yarilo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}-telemetry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry
spec:
  type: ClusterIP
  ports:
    - name: telemetry
      port: {{ .Values.service.telemetryPort }}
      targetPort: telemetry
      protocol: TCP
  selector:
    {{- include "yarilo.selectorLabels" . | nindent 4 }}
