{{- if .Values.components.warden.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}-warden
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.componentLabels" (dict "root" . "component" "warden") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: warden
      port: 9101
      targetPort: warden
      protocol: TCP
  selector:
    {{- include "yarilo.componentSelectorLabels" (dict "root" . "component" "warden") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}-warden-telemetry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.componentLabels" (dict "root" . "component" "warden") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: telemetry
      port: 8080
      targetPort: telemetry
      protocol: TCP
  selector:
    {{- include "yarilo.componentSelectorLabels" (dict "root" . "component" "warden") | nindent 4 }}
{{- end }}
