{{- if .Values.components.saslLogin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}-sasl-login-telemetry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.componentLabels" (dict "root" . "component" "sasl-login") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: telemetry
      port: 8080
      targetPort: telemetry
      protocol: TCP
  selector:
    {{- include "yarilo.componentSelectorLabels" (dict "root" . "component" "sasl-login") | nindent 4 }}
{{- end }}
