{{- if .Values.components.quotaStatus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}-quota-status
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.componentLabels" (dict "root" . "component" "quota-status") | nindent 4 }}
  {{- with .Values.components.quotaStatus.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.components.quotaStatus.service.type | default "ClusterIP" }}
  ports:
    - name: policy
      port: {{ .Values.components.quotaStatus.servicePort }}
      targetPort: policy
      protocol: TCP
  selector:
    {{- include "yarilo.componentSelectorLabels" (dict "root" . "component" "quota-status") | nindent 4 }}
{{- end }}
