{{- if .Values.telemetry.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "yarilo.fullname" . }}
  namespace: {{ .Values.telemetry.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "yarilo.labels" . | nindent 4 }}
    {{- with .Values.telemetry.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "yarilo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: yarilo
  endpoints:
    - port: telemetry
      path: /metrics
      interval: {{ .Values.telemetry.serviceMonitor.interval }}
{{- end }}
