{{- if .Values.mysql.bundled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.componentLabels" (dict "root" . "component" "mysql") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    {{- include "yarilo.componentSelectorLabels" (dict "root" . "component" "mysql") | nindent 4 }}
{{- end }}
