package main

// cannedGoodEmail is an Email/get answer in which every form is right. It is
// what the live check should receive, kept here so the reader of it can be
// exercised without a cluster.
const cannedGoodEmail = `{"methodResponses":[["Email/get",{"accountId":"u1@example.com","state":"0","notFound":[],"list":[{"id":"email-1","headers":[{"name":"Subject","value":" =?utf-8?q?caf=C3=A9?="},{"name":"From","value":" \"say \\\"hi\\\"\" <sender@example.com>"},{"name":"To","value":" Team:alice@example.com,bob@example.com;, carol@example.com"},{"name":"Date","value":" Tue, 05 Aug 2026 09:30:00 +0200"},{"name":"Message-Id","value":" <smoke-header-forms@yarilo.invalid>"},{"name":"List-Unsubscribe","value":" <https://example.com/u/1>, <mailto:un@example.com>"},{"name":"X-Spam-Status","value":" No, score=-2.1 required=5.0"},{"name":"Received","value":" from a.example.com\r\n by b.example.com;\r\n Tue, 05 Aug 2026 09:29:00 +0200"},{"name":"Received","value":" from c.example.com by d.example.com"}],"header:List-Unsubscribe":" <https://example.com/u/1>, <mailto:un@example.com>","header:List-Unsubscribe:asURLs":["https://example.com/u/1","mailto:un@example.com"],"header:X-Spam-Status":" No, score=-2.1 required=5.0","header:Subject":" =?utf-8?q?caf=C3=A9?=","header:Subject:asText":"café","header:Message-Id:asMessageIds":["smoke-header-forms@yarilo.invalid"],"header:Date:asDate":"2026-08-05T07:30:00Z","header:From:asAddresses":[{"name":"say \"hi\"","email":"sender@example.com"}],"header:To:asGroupedAddresses":[{"name":null,"addresses":[]},{"name":"Team","addresses":[{"name":null,"email":"alice@example.com"},{"name":null,"email":"bob@example.com"}]},{"name":null,"addresses":[{"name":null,"email":"carol@example.com"}]}],"header:Received":" from c.example.com by d.example.com","header:Received:all":[" from a.example.com\r\n by b.example.com;\r\n Tue, 05 Aug 2026 09:29:00 +0200"," from c.example.com by d.example.com"],"header:Received:asText:all":["from a.example.com by b.example.com; Tue, 05 Aug 2026 09:29:00 +0200","from c.example.com by d.example.com"],"header:X-Nonexistent":null,"header:X-Nonexistent:all":[]}]},"c0"]]}`

// cannedWrongURLType differs in one field: asURLs answers with the raw string
// instead of an array, which is the failure that form exists to catch and the
// one a substring check would miss.
const cannedWrongURLType = `{"methodResponses":[["Email/get",{"accountId":"u1@example.com","state":"0","notFound":[],"list":[{"id":"email-1","headers":[{"name":"Subject","value":" =?utf-8?q?caf=C3=A9?="},{"name":"From","value":" \"say \\\"hi\\\"\" <sender@example.com>"},{"name":"To","value":" Team:alice@example.com,bob@example.com;, carol@example.com"},{"name":"Date","value":" Tue, 05 Aug 2026 09:30:00 +0200"},{"name":"Message-Id","value":" <smoke-header-forms@yarilo.invalid>"},{"name":"List-Unsubscribe","value":" <https://example.com/u/1>, <mailto:un@example.com>"},{"name":"X-Spam-Status","value":" No, score=-2.1 required=5.0"},{"name":"Received","value":" from a.example.com\r\n by b.example.com;\r\n Tue, 05 Aug 2026 09:29:00 +0200"},{"name":"Received","value":" from c.example.com by d.example.com"}],"header:List-Unsubscribe":" <https://example.com/u/1>, <mailto:un@example.com>","header:List-Unsubscribe:asURLs":" <https://example.com/u/1>, <mailto:un@example.com>","header:X-Spam-Status":" No, score=-2.1 required=5.0","header:Subject":" =?utf-8?q?caf=C3=A9?=","header:Subject:asText":"café","header:Message-Id:asMessageIds":["smoke-header-forms@yarilo.invalid"],"header:Date:asDate":"2026-08-05T07:30:00Z","header:From:asAddresses":[{"name":"say \"hi\"","email":"sender@example.com"}],"header:To:asGroupedAddresses":[{"name":null,"addresses":[]},{"name":"Team","addresses":[{"name":null,"email":"alice@example.com"},{"name":null,"email":"bob@example.com"}]},{"name":null,"addresses":[{"name":null,"email":"carol@example.com"}]}],"header:Received":" from c.example.com by d.example.com","header:Received:all":[" from a.example.com\r\n by b.example.com;\r\n Tue, 05 Aug 2026 09:29:00 +0200"," from c.example.com by d.example.com"],"header:Received:asText:all":["from a.example.com by b.example.com; Tue, 05 Aug 2026 09:29:00 +0200","from c.example.com by d.example.com"],"header:X-Nonexistent":null,"header:X-Nonexistent:all":[]}]},"c0"]]}`
