apiVersion: v2
name: yarilo
description: Production-grade IMAP/POP3/Submission mail server
type: application
version: 1.23.0
appVersion: "1.23.0"
keywords:
  - imap
  - submission
  - lmtp
  - mail
icon: https://raw.githubusercontent.com/0kaba0hub/yarilo/main/docs/icon.svg
home: https://github.com/0kaba0hub/yarilo
sources:
  - https://github.com/0kaba0hub/yarilo
