apiVersion: v2
name: yarilo
description: Production-grade IMAP/POP3/Submission mail server
type: application
version: 2.0.49
appVersion: "2.1.49"
keywords:
  - imap
  - submission
  - lmtp
  - mail
icon: https://raw.githubusercontent.com/0kaba0hub/yarilo/main/docs/icon.svg
home: https://github.com/0kaba0hub/yarilo
sources:
  - https://github.com/0kaba0hub/yarilo
